Add NodeletLazy abstract class for lazy transport
ros/nodelet_core pull request #45
Opened 2016-08-10 06:41 UTC by wkentaro

This class is to crete nodelet for 'lazy' transport.
Class for Python node is already merged in kinetic-devel branch of topic_tools.  https://github.com/ros/ros_comm/pull/713

Lazy transport is a essential feature for perception nodelets that handle image and point cloud, because
the processing should run only when it is necessary to reduce the CPU load.

2016-08-10 06:45 UTC, wkentaro commented
Maintainers, could you please review this?
Possibly, the first step to view how it works is below:

```bash
cd test_nodelet_topic_tools
catkin build --this
rostest test/test_nodelet_lazy.launch --text
```

2016-08-23 04:35 UTC, wkentaro commented
Any comments, please/

2016-08-23 05:38 UTC, mikaelarguedas commented
sorry for the late reply, will review this shortly.
Thanks!

2016-09-09 16:53 UTC, wkentaro commented
Friendly ping.

2016-09-19 15:44 UTC, wkentaro commented
ping

2016-09-19 16:58 UTC, mikaelarguedas commented
finally got back decent internet, will review this today, sorry for the very long wait

2016-09-19 19:04 UTC, mikaelarguedas commented on nodelet_topic_tools/include/nodelet_topic_tools/nodelet_lazy.h
> +      ros::WallDuration(5),
Would it make sense to expose this timer as a ros param ?

2016-09-19 19:04 UTC, mikaelarguedas commented on nodelet_topic_tools/include/nodelet_topic_tools/nodelet_lazy.h
> +      ever_subscribed_ = true;
set flag after subscribe succeeded

2016-09-19 19:04 UTC, mikaelarguedas commented on nodelet_topic_tools/include/nodelet_topic_tools/nodelet_lazy.h
> +            ever_subscribed_ = true;
same as above

2016-09-19 19:06 UTC, mikaelarguedas commented on nodelet_topic_tools/include/nodelet_topic_tools/nodelet_lazy.h
> +    * created by this method.
Rephrase this as a single sentence? the meaning of "Publishers which are created by this method" is unclear to me. Did you mean "update the list of Publishers created by this method" ?

2016-09-19 19:08 UTC, mikaelarguedas requested changes

2016-09-19 19:08 UTC, mikaelarguedas commented
@wkentaro Code looks good to me overall, a few nicktip comments to address/clarify but all of them are cosmetics.

2016-09-19 19:26 UTC, wkentaro commented
Fixed.

2016-09-19 21:06 UTC, mikaelarguedas commented
great! thanks for iterating on this

2016-09-19 21:06 UTC, mikaelarguedas approved these changes

2016-09-19 21:28 UTC, merged

2016-09-19 21:31 UTC, wkentaro commented
Thanks!